---
# RUN WITH -e "ec2_access_key=KEY ec2_secret_key=SECRET"
# WORK IN PROGRESS!
# Automatically configures the right inventories per group
# this avoids each group having to manually configure their server
- hosts: tag_type_buildserver
  gather_facts: yes
  tasks:
    - name: Gather ec2 facts
      action: ec2_facts
      register: result
    - debug: var=result
    - name: configure staging inventory
      template:
        src: templates/inventory_template.j2
        dest: "{{ item.target }}"
        mode: 0664
      with_items:
        - { environment: 'acc', target: '/home/ubuntu/euro-bookies-2016/ansible/staging/staging' }
        - { environment: 'prd', target: '/home/ubuntu/euro-bookies-2016/ansible/production/production' }
    - debug: var
