---
- name: create path to github organization
  file:
    path: /var/lib/jenkins/jobs/{{ repo_owner }}
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755
- name: installing github organization of {{ repo_owner }}
  template:
    src: jenkins/jobs/github_organization_config/config.xml   # the file with jinja2 template directives
    dest: /var/lib/jenkins/jobs/{{ repo_owner }}/config.xml   # the target location
    owner: jenkins                                            # file owner
    group: jenkins                                            # file group
    mode: 0644                                                # rw-r--r--   (first digit is for special permissions, setuid, setgid, sticky)
    force: no
    # Handlers are executed in order. We want the restart of parent roles (karlmdavis.jenkins2) to run first, then
    # after that reboot we also do a reboot (for safety, in case the parent role didn't trigger a handler) and trigger
    # a HTTP Post call, this "Trigger build" must be the last call on jenkins. otherwise reboots will cancel this trigger
  notify:
    - "Restart Service 'jenkins'"
    - "Trigger build"
