# installs the public key found .ssh/id_rsa.pub on all servers, make sure id_rsa.pub exists!
# ansible-playbook -i <inventory-file> install-ssh-key.yml --ask-pass
# this needs to be run only once
---
- hosts: all
  tasks:
    - name: installing ansibles public key on all servers
      authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
